### ISSUE TITLE
Error while accessing PixelData bytes

### ISSUE THREAD

**Issue by scandav** [Enet4/dicom-rs#336]
Hi, I am following the example reported in the crate docs.

```rust 
use dicom::core::Tag;
use dicom::object::{open_file, Result};

let obj = open_file("0001.dcm")?;
let pixel_data_bytes = obj.element(Tag(0x7FE0, 0x0010))?.to_bytes()?;
```

I am getting the following error: `bad value cast: requested bytes but value is PixelSequence`

Dicom file from [here](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/NXTSQ6): [IMG00039_38464LAD_LAO.dcm.zip](https://github.com/Enet4/dicom-rs/files/11147926/IMG00039_38464LAD_LAO.dcm.zip)

**Comment by Enet4** [comment]
Hello! Since that instance is in JPEG Lossless, the pixel data is encoded as a sequence of pixel data fragments. That behavior is by design, because `to_bytes` only works for non-sequence values.

If you intend to retrieve the raw data within the fragments comprising the frames, you would instead retrieve the items of the pixel data sequence (`.items()`). Note that [`dicom-pixeldata`](https://docs.rs/dicom-pixeldata/latest/dicom_pixeldata/) provides a higher level API for decoding the pixel data, regardless of transfer syntax.

**Comment by scandav** [comment]
Thank you for your answer, understood.

As I have to compute a checksum on the image content of a set of dicoms, I would not need to decode the images with `dicom-pixeldata` - which is by the way the solution I have implemented so far. 

I was wondering whether there was an option to retrieve the raw bytes of the bulk data as read from the file. That would make it much faster.

**Comment by Enet4** [comment]
> Update: I have tried with `.items()` as you suggested above but it returns `None`

Sorry for the confusion, it would be `.value().fragments()` instead. `items()` provides data set items only. This should hopefully be enough to compute a digest of all raw fragment bytes. They do not even have to be collected into one flat array if you use a [digest `Context`](https://docs.rs/ring/0.16.20/ring/digest/struct.Context.html).

---

Under internal consideration, there might be room for an extension to the dicom-object API that would support multi-step loading of DICOM data sets, which would also let the consumer know the position where certain elements start and revert to plain reader cursors on larger values.

**Comment by scandav** [comment]
> Sorry for the confusion, it would be `.value().fragments()` instead. 

I have tried what you suggested but it seems like the `Value::PixelSequence` has no `fragments` method. It seems to have only a private `fragments` attribute.

https://github.com/Enet4/dicom-rs/blob/c1644cf355f160946f947273bb89283546be2c98/core/src/value/mod.rs#L66-L71

**Comment by Enet4** [comment]
Hmm right, the method is still not available upstream, but since the field is inside a public enum variant, it is not private. It just needs some pattern matching to retrieve it right now:

```rust
match obj.element()?.value() {
    DicomValue::Primitive(value) => {
        todo!("value.to_bytes() works here")
    },
    DicomValue::PixelSequence { fragments, .. } => {
        todo!("fragments available")
    },
    DicomValue::Sequence { .. } => panic!("illegal value type for pixel data"),
}
```

**Comment by scandav** [comment]
It works - and digest on fragments is indeed 30x faster than decoding the pixel data! Thanks a lot for your work! 😃 💯

**Comment by Enet4** [comment]
Glad I could be of assistance! I will be closing this issue, but this exchange has certainly brought some ideas which can derive into more contributions in the future.
